generatorName: java-helidon-client
outputDir: samples/client/petstore/java-helidon-client/
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
additionalProperties:
  artifactId: petstore-helidon
  hideGenerationTimestamp: "true"
  configureAuth: "false"
  build: "all"
  test: "spock"
  requiredPropertiesInConstructor: "false"
  visitable: "true"
